server:
  port: 8080

spring:
  application:
    name: e-commerce-api
  profiles:
    active: local

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/ecommerce?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

# Configurações da aplicação
app:
  auth:
    token:
      expirationInMilis: 3600000
      jwtSecret: 92929949530403043912012012A23BE23CE2D2D21F11A
  images:
    allowed-types: image/jpeg,image/png,image/webp
  upload:
    dir: upload/images
